# baseURL = "https://joehowarth.github.io/"
# languageCode = "en-us"
# title = "Joe Howarth"
# theme = "beautifulhugo"
# pygmentsCodeFencesGuessSyntax = true

# [params]
# useHLJS = true

baseurl = "https://joehowarth.github.io"
DefaultContentLanguage = "en"
title = "Joe Howarth"
theme = "beautifulhugo"
metaDataFormat = "yaml"

[Params]
#  homeTitle = "Beautiful Hugo Theme" # Set a different text for the header on the home page
  subtitle = "code, societal modelling, lighting"
  logo = "img/avatar.png" # Expecting square dimensions
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  wordCount = true
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = false
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Joe Howarth"
#   website = "yourwebsite.com"
  email = "JosepheHowarth@gmail.com"
  facebook = "joseph.e.howarth"
  #   googleplus = "+username" # or xxxxxxxxxxxxxxxxxxxxx
  github = "JoeHowarth"
  twitter = "JoeHowarth20"
#   linkedin = "username"

[[menu.main]]
    name = "Blog"
    url = "posts/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3

[[menu.main]]
    identifier = "sim"
    name = "Historical Simulation"
    weight = 2

[[menu.main]]
    parent = "sim"
    name = "Population Design"
    url = "posts/populationdesign"
    weight = 1

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3
